### ISSUE TITLE
Blockchain_info_WHMCS_Payment_Gateway billing error (Error ID: 1)

### ISSUE THREAD

**Issue by hilary05** [mobo12/Blockchain_info_WHMCS_Payment_Gateway#1]
Hello,

thank you for the module. am truly gratefully. am using WHMCS V7.0.1 and i have uploaded all the files for this payment module but i get error when a client wants to make payment. the error says **An error has occurred, please contact Billing or choose a different payment method. (Error ID: 1)** 

Please can you explain what the issue is and how to fix this. 

Thank You

**Comment by mobo12** [comment]
make sure you added valid bitcoin address and amount is more that 0.0005 btc.

**Comment by hilary05** [comment]
Hello, i have checked and the bitcoin address is correct **1GRnikh4DKV5AXRqam23Sdsf8k9qYcSViK** Also the amount on the invoice on my WHMCS V7.0.1 is $21 which is 0.0281 Btc. I was just thinking maybe its not compatible with WHMCS V7.0.1. Please i will really appreciate your great effort to fix this issue.

**Comment by big89** [comment]
Hello, we are working on WHMCS Blockchain Payment Module. Contact us if anyone wants to use this. Thanks !!!
